workflows:
  android-app:
    name: Android App
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.example.scamcalldetector"
      java: 11

    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Set up project structure
        script: |
          mkdir -p src/main/res/values
          echo '<?xml version="1.0" encoding="utf-8"?>
          <resources>
              <string name="app_name">Scam Call Detector</string>
          </resources>' > src/main/res/values/strings.xml

      - name: Set up Gradle wrapper
        script: |
          mkdir -p gradle/wrapper
          cd gradle/wrapper
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          wget https://raw.githubusercontent.com/gradle/gradle/v7.6.0/gradle/wrapper/gradle-wrapper.jar
          cd ../..

      - name: Create gradle-wrapper.properties
        script: |
          echo "distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists" > gradle/wrapper/gradle-wrapper.properties

      - name: Fix line endings and permissions
        script: |
          apt-get update && apt-get install -y dos2unix
          dos2unix gradlew
          chmod +x gradlew

      - name: Debug setup
        script: |
          pwd
          ls -la
          echo "Content of settings.gradle:"
          cat settings.gradle
          echo "Content of build.gradle:"
          cat build.gradle

      - name: Build Android app
        script: |
          ./gradlew clean assembleDebug --info --stacktrace
    artifacts:
      - build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
