workflows:
  android-app:
    name: Android App
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.example.scamcalldetector"
      java: 11

    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Set up Gradle wrapper
        script: |
          mkdir -p gradle/wrapper
          cd gradle/wrapper
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          wget https://raw.githubusercontent.com/gradle/gradle/v7.6.0/gradle/wrapper/gradle-wrapper.jar
          cd ../..

      - name: Create gradle-wrapper.properties
        script: |
          echo "distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists" > gradle/wrapper/gradle-wrapper.properties

      - name: Fix line endings
        script: |
          apt-get update && apt-get install -y dos2unix
          dos2unix gradlew

      - name: Set up gradle permissions
        script: |
          chmod +x gradlew

      - name: Debug - List files
        script: |
          echo "Current directory:"
          pwd
          echo "\nDirectory contents:"
          ls -la
          echo "\nGradle wrapper contents:"
          ls -la gradle/wrapper/

      - name: Build Android app
        script: |
          ./gradlew clean assembleDebug --stacktrace --info
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - paul.hague@blackdice.ai
        notify:
          success: true
          failure: true
