workflows:
  android-app:
    name: Android App
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.example.scamcalldetector"
      java: 11

    scripts:
      - name: Create project structure
        script: |
          # Create necessary directories
          mkdir -p src/main/java/com/example/scamcalldetector
          mkdir -p src/main/res/values
          mkdir -p src/main/res/layout
          mkdir -p gradle/wrapper

          # Create local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

          # Set up Gradle wrapper
          cd gradle/wrapper
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          wget https://raw.githubusercontent.com/gradle/gradle/v7.6.0/gradle/wrapper/gradle-wrapper.jar
          cd ../..

          # Create gradle-wrapper.properties
          echo "distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists" > gradle/wrapper/gradle-wrapper.properties

          # Fix permissions
          chmod +x gradlew

      - name: Build Android app
        script: |
          # Clean and build
          ./gradlew clean
          ./gradlew assembleDebug --no-daemon --stacktrace
    artifacts:
      - build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
